ViewModels/CreateRoleViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BeckITEjendomsmæglerApplikation.ViewModels
{
    public class CreateRoleViewModel
    {
        [Required]
        public string RoleName { get; set; }
    }
}

ViewModels/EditRolesViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BeckITEjendomsmæglerApplikation.ViewModels
{
    public class EditRolesViewModel
    {

        public EditRolesViewModel()
        {
            Users = new List<string>();
        }
        public string Id { get; set; }

        [Required(ErrorMessage = "Role Name is required")]
        public string RoleName { get; set; }

        public List<string> Users { get; set; }
    }
}

ViewModels/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BeckITEjendomsmæglerApplikation.ViewModels
{
    public class LoginViewModel
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Display(Name = "Husk mig")]
        public bool RememberMe { get; set; }

    }
}

ViewModels/RegistrationViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BeckITEjendomsmæglerApplikation.ViewModels
{
    public class RegistrationViewModel
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Confirm Password")]
        [Compare("Password",
            ErrorMessage = "Passwords do not match.")]
        public string ConfirmPassword { get; set; }

        public string UserRole { get; set; }
    }


}

Controllers/AddressController.cs
using System;
using System.Threading.Tasks;
using BeckITEjendomsmæglerApplikation.DatabaseContext;
using BeckITEjendomsmæglerApplikation.Models;
using BeckITEjendomsmæglerApplikation.Models.AddressHyperlinks;
using BeckITEjendomsmæglerApplikation.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BeckITEjendomsmæglerApplikation.Controllers
{
    public class AddressController : Controller
    {

        private readonly ApplicationDbContext context;
        public AddressController(ApplicationDbContext dbContext)
        {
            this.context = dbContext;
        }

        //GET
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var addresses = context.Addresses
                .Include(c => c.Boliga)
                .Include(c => c.Boligsiden)
                .AsNoTracking();
            return View(await addresses.ToListAsync());
        }

        [HttpGet]
        public ViewResult Create()
        {
            return View();
        }      

        //POST
        [HttpPost]
        public IActionResult Create(CreateAddressViewModel model)
        {
            if (ModelState.IsValid)
            {
                Address newAddress = new Address
                {
                    Street = model.Street,
                    Zipcode = model.Zipcode,
                    StartLiggetid = model.StartLiggetid,
                    Boligsiden = model.BoligsidenAddresse,
                    Boliga = model.BoligaAddresse,
                    DateOfInsertion = model.DateOfInsertion
                };

                context.AddRange(newAddress);
                context.SaveChanges();
                return RedirectToAction("index", new { id = newAddress.AddressId });

            }

            return View();
        }

        //DELETE
        public async Task<IActionResult> Delete(int? id)
        {
            var address = await context.Addresses.FindAsync(id);
            context.Addresses.Remove(address);
            await context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/AdministrationController.cs
using BeckITEjendomsmæglerApplikation.Models;
using BeckITEjendomsmæglerApplikation.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BeckITEjendomsmæglerApplikation.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdministrationController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<ApplicationUser> userManager;

        public AdministrationController(RoleManager<IdentityRole> roleManager,
                                        UserManager<ApplicationUser> userManager)
        {
            this.roleManager = roleManager;            
            this.userManager = userManager;
        }

        [HttpGet]
        public IActionResult CreateRole()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateRole(CreateRoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                IdentityRole identityRole = new IdentityRole
                {
                    Name = model.RoleName
                };

                IdentityResult result = await roleManager.CreateAsync(identityRole);

                if (result.Succeeded)
                {
                    return RedirectToAction("ListRoles", "administration");
                }

                foreach (IdentityError error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> EditRole(string id)
        {
            var role = await roleManager.FindByIdAsync(id);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {id} cannot be found";
                return View("NotFound");
            }

            var model = new EditRolesViewModel
            {
                Id = role.Id,
                RoleName = role.Name
            };

            foreach (var user in userManager.Users)
            {
                if (await userManager.IsInRoleAsync(user, role.Name))
                {
                    model.Users.Add(user.UserName);
                }
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditRole(EditRolesViewModel model)
        {
            var role = await roleManager.FindByIdAsync(model.Id);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {model.Id} cannot be found";
                return View("NotFound");
            }
            else
            {
                role.Name = model.RoleName;
                var result = await roleManager.UpdateAsync(role);

                if (result.Succeeded)
                {
                    return RedirectToAction("ListRoles");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

                return View(model);
            }            
        }

        [HttpGet]
        public async Task<IActionResult> EditUsersInRole(string roleId)
        {
            ViewBag.roleId = roleId;

            var role = await roleManager.FindByIdAsync(roleId);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {roleId} cannot be found";
                return View("NotFound");
            }

            var model = new List<UserRoleViewModel>();

            foreach (var user in userManager.Users)
            {
                var userRoleViewModel = new UserRoleViewModel
                {
                    UserId = user.Id,
                    Name = user.UserName
                };

                if (await userManager.IsInRoleAsync(user, role.Name))
                {
                    userRoleViewModel.IsSelected = true;
                }
                else
                {
                    userRoleViewModel.IsSelected = false;
                }

                model.Add(userRoleViewModel);
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditUsersInRole(List<UserRoleViewModel> model, string roleId)
        {
            var role = await roleManager.FindByIdAsync(roleId);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {roleId} cannot be found";
                return View("NotFound");
            }

            for (int i = 0; i < model.Count; i++)
            {
                var user = await userManager.FindByIdAsync(model[i].UserId);

                IdentityResult result = null;

                if (model[i].IsSelected && !(await userManager.IsInRoleAsync(user, role.Name)))
                {
                    result = await userManager.AddToRoleAsync(user, role.Name);
                }
                else if (!model[i].IsSelected && await userManager.IsInRoleAsync(user, role.Name))
                {
                    result = await userManager.RemoveFromRoleAsync(user, role.Name);
                }
                else
                {
                    continue;
                }

                if (result.Succeeded)
                {
                    if (i < (model.Count - 1))                    
                        continue;                    
                    else
                        return RedirectToAction("EditRole", new { Id = roleId });                    
                }
            }

            return RedirectToAction("EditRole", new { Id = roleId });
        }

        public IActionResult ListRoles()
        {
            var roles = roleManager.Roles;
            return View(roles);
        }
    }
}

Controllers/CalendarController.cs
using BeckITEjendomsmæglerApplikation.DatabaseContext;
using Microsoft.AspNetCore.Mvc;
using BeckITEjendomsmæglerApplikation.Models;

namespace BeckITEjendomsmæglerApplikation.Controllers
{
    public class CalendarController : Controller
    {
        private readonly ApplicationDbContext context;
        public CalendarController(ApplicationDbContext dbContext)
        {
            this.context = dbContext;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/FileUploadController.cs
using BeckITEjendomsmæglerApplikation.DatabaseContext;
using BeckITEjendomsmæglerApplikation.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace BeckITEjendomsmæglerApplikation.Controllers
{
    public class FileUploadController : Controller
    {
        private readonly ApplicationDbContext context;
        public FileUploadController(ApplicationDbContext dbContext)
        {
            this.context = dbContext;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var files = context.Files
                .AsNoTracking();
            return View(await files.ToListAsync());
        }
    }
}

Controllers/SearchController.cs
using BeckITEjendomsmæglerApplikation.DatabaseContext;
using BeckITEjendomsmæglerApplikation.Models;
using BeckITEjendomsmæglerApplikation.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BeckITEjendomsmæglerApplikation.Controllers
{
    public class SearchController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SearchController(ApplicationDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult Search()
        {
            SearchViewModel m = new SearchViewModel();
            return View(m);
        }

        [HttpPost]
        public async Task<IActionResult> Search(SearchViewModel model)
        {
            if (ModelState.IsValid)
            {
                var addresses = _context.Addresses
                .Include(c => c.Boliga)
                .Include(c => c.Boligsiden)
                .Include(c => c.Type)
                .AsNoTracking();
                var addList = await addresses.ToListAsync();                
                var resultList = new List<Address>();
                
                if (model.Andelsbolig == true)
                {
                    foreach (var n in addList.Where(s => s.Type.BoligTypeNavn == "Andelsbolig"))
                    {
                        resultList.Add(n);
                    }
                }
                if (model.Ejerlejlighed == true)
                {
                    foreach (var n in addList.Where(s => s.Type.BoligTypeNavn == "Ejerlejlighed"))
                    {
                        resultList.Add(n);
                    }
                }
                if (model.Fritidsbolig == true)
                {
                    foreach (var n in addList.Where(s => s.Type.BoligTypeNavn == "Fritidsbolig"))
                    {
                        resultList.Add(n);
                    }
                }
                if (model.Fritidsgrund == true)
                {
                    foreach (var n in addList.Where(s => s.Type.BoligTypeNavn == "Fritidsgrund"))
                    {
                        resultList.Add(n);
                    }
                }
                if (model.Helårsgrund == true)
                {
                    foreach (var n in addList.Where(s => s.Type.BoligTypeNavn == "Helårsgrund"))
                    {
                        resultList.Add(n);
                    }
                }
                if (model.Landejendom == true)
                {
                    foreach (var n in addList.Where(s => s.Type.BoligTypeNavn == "Landejendom"))
                    {
                        resultList.Add(n);
                    }
                }
                if (model.Rækkehus == true)
                {
                    foreach (var n in addList.Where(s => s.Type.BoligTypeNavn == "Rækkehus"))
                    {
                        resultList.Add(n);
                    }
                }
                if (model.Villa == true)
                {
                    foreach (var n in addList.Where(s => s.Type.BoligTypeNavn == "Villa"))
                    {
                        resultList.Add(n);
                    }

                }
                if (model.Villalejlighed == true)
                {
                    foreach (var n in addList.Where(s => s.Type.BoligTypeNavn == "Villalejlighed"))
                    {
                        resultList.Add(n);
                    }
                }

                if (model.SlLiggetid == 0)
                {
                    resultList = resultList.Where(x => x.Liggetid >= model.StLiggetid).ToList();
                }
                else
                {
                    resultList = resultList.Where(x => x.Liggetid >= model.StLiggetid
                                            & x.Liggetid <= model.SlLiggetid).ToList();
                }

                if (!String.IsNullOrEmpty(model.Query))
                {
                    resultList = resultList.Where(x => x.Street.ToLower().Contains(model.Query.ToLower())
                                                        || x.Zipcode.Contains(model.Query.ToLower())
                                                        /*|| x.City.Contains(model.Query.ToLower())*/
                                                        /*|| x.County.Contains(model.Query.ToLower())*/
                                                        /*|| x.Landsdel.Contains(model.Query.ToLower())*/).ToList();
                }
                model.rList = resultList;
                return View(model);
            }
            return View(model);
        }
    }
}

Views/Shared/CreateRole.cshtml
@model CreateRoleViewModel
@{
    ViewBag.Title = "Create New Role";
}

<h1>User Registration</h1>

<div class="row">
    <div class="col-md-12">
        <form method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RoleName"></label>
                <input asp-for="RoleName" class="form-control" />
                <span asp-validation-for="RoleName" class="text-danger"></span>
            </div>
            <button style="width:auto" type="submit" class="btn btn-primary">CreateRole</button>
        </form>
    </div>
</div>

Views/Shared/EditRole.cshtml
@model EditRolesViewModel

@{ 
    ViewBag.Title = "Edit Role";
}

<h1>Edit Role</h1>

<form method="post" class="mt-3">
    <div class="form-group row">
        <label asp-for="Id" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Id" disabled class="form-control"/>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="RoleName" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="RoleName" class="form-control"/>
            <span asp-validation-for="RoleName" class="text-danger"></span>
        </div>
    </div>

    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-check-group now">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Update</button>
            <a asp-action="ListRoles" class="btn btn-primary">Back</a>
        </div>
    </div>

    <div class="card">
        <div class="card-header">
            <h3>Users in this role</h3>
        </div>
        <div class="card-body">
            @if (Model.Users.Any())
            {
                foreach (var user in Model.Users)
                {
                    <h5 class="card-title">@user</h5>
                }
            }
            else
            {
                <h5 class="card-title">No users with this role</h5>
            }
        </div>
        <div class="card-footer">
            <a asp-action="EditUsersInRole" asp-controller="Administration" asp-route-roleId="@Model.Id" class="btn btn-primary" style="width:auto">Add or remove users</a>
        </div>
    </div>
</form>

Views/Shared/EditUsersInRole.cshtml
@model List<UserRoleViewModel>

@{ 
    var roleId = ViewBag.roleId;
}

<form method="post">
    <div class="Card mb-3">
        <div class="card-header">
            <h2>Assign users to this role</h2>
        </div>
        <div class="card-body">
            @for (int i = 0; i < Model.Count; i++)
            {
            <div class="form-check m-1">
                <input type="hidden" asp-for="@Model[i].UserId" />
                <input type="hidden" asp-for="@Model[i].Name" />
                <input asp-for="@Model[i].IsSelected" class="form-check-input" />
                <label asp-for="@Model[i].IsSelected" class="form-check-label">
                    @Model[i].Name
                </label>
            </div>
            }
        </div>
        <div class="card-footer">
            <input type="submit" value="Update" class="img-thumbnail btn-primary" style="width:auto"/>
            <a class="btn btn-primary" style="width:auto" asp-action="EditRole" asp-route-id="@roleId">Cancel</a>
        </div>
    </div>
</form>

Views/Shared/ListRoles.cshtml
@model IEnumerable<IdentityRole>

@{
    ViewBag.Title = "All Roles";
}

<h1>All Roles</h1>

@if (Model.Any())
{
    <a class="btn btn-primary mb-3" style="width:auto" asp-controller="administration" asp-action="CreateRole">Add new role</a>
    foreach (var role in Model)
    {
        <div class="Card mb-3">
            <div class="card-header">
                Role Id : @role.Id
            </div>
            <div class="card-body">
                <h5 class="card-title">@role.Name</h5>
            </div>
            <div class="card-footer">
                <a class="btn btn-primary" style="width:auto" asp-controller="Administration" asp-action="EditRole" asp-route-id="@role.Id">Edit</a>
                <a class="btn btn-danger" style="width:auto" asp-controller="Administration" asp-action="DeleteRole" asp-route-id="@role.Id">Delete</a>
            </div>
        </div>
    }

}
else
{
    <div class="Card">
        <div class="card-header">
            No roles yet
        </div>
        <div class="card-body">
            <h5 class="card-title">
                Press button to create a role
            </h5>
            <a class="btn btn-primary" style="width:auto" asp-controller="Administration" asp-action="CreateRole">Create Role</a>
        </div>
    </div>

}

Views/Shared/Login.cshtml
@model LoginViewModel
@{
    ViewBag.Title = "User Login";
}

<h1>User Login</h1>

<div class="row">
    <div class="col-md-12">
        <form method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label asp-for="RememberMe">
                        <input asp-for="RememberMe" />
                        @Html.DisplayNameFor(m => m.RememberMe)
                    </label>                    
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Login</button>
        </form>
    </div>
</div>

Views/Shared/NotFound.cshtml
@{
    ViewBag.Title = "Not Found";
}

<h1>@ViewBag.ErrorMessage</h1>

<a asp-action="index" asp-controller="Home">
    Click here to navigate to the home page
</a>

Views/Shared/Registration.cshtml
@model RegistrationViewModel
@{
    ViewBag.Title = "Registrering";
}

<h1>Bruger registrering</h1>

<div class="row">
    <div class="col-md-12">
        <form method="post" asp-controller="Account" asp-action="Registration">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control"/>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password"></label>
                <input asp-for="Password" class="form-control"/>
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ConfirmPassword"></label>
                <input asp-for="ConfirmPassword" class="form-control"/>
                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
            </div>
            <select asp-for="UserRole">
                <option  value="Ejendomsmægler">Ejendomsmægler</option>
                <option value="Standard">Standard</option>
            </select>
            <button type="submit" class="btn btn-primary">Register</button>
        </form>
    </div>
</div>

Views/Shared/Search.cshtml
@model SearchViewModel
@{
    ViewBag.Title = "Search";
}
<head>
    <style>
        div.a {
            display: inline-block
        }
    </style>
</head>
<h1>Søge funktion</h1>
<div class="row">
    <div class="col-md-12">
        <form method="post" asp-controller="Search" asp-action="Search">

            <div class="form-group">
                <label asp-for="Query"></label>
                <input asp-for="Query" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="StLiggetid"></label>
                <input asp-for="StLiggetid" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="SlLiggetid"></label>
                <input asp-for="SlLiggetid" class="form-control" />
            </div>
            <div>
                @for (int i = 0; i < Model.btList.Count; i++)
                {
                    <input type="checkbox" asp-for="@Model.btList[i].IsChecked" name="@Model.btList[i].TName" />
                    <label method="get" asp-for="@Model.btList[i].IsChecked">
                        @Model.btList[i].TName
                    </label>
                    <input type="hidden" asp-for="@Model.btList[i].IsChecked" name="@Model.btList[i].TName" value="false"/>                    
                }
            </div>
            <button type="submit" class="btn btn-primary">Søg</button>
        </form>
    </div>
    <table class="table">
        @*<thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.rList.Street)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Zipcode)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Liggetid)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Boligsiden.BoligsidenHyperlink)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Boliga.BoligaHyperlink)
                    </th>
                </tr>
            </thead>*@
        <tbody>
            @if (Model.rList != null)
            {
                @foreach (var item in Model.rList)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Street)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Zipcode)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Liggetid)
                        </td>
                        <td>
                            <a href="@Html.DisplayFor(modelItem => item.Boligsiden.BoligsidenHyperlink)" target="_blank">@Html.DisplayFor(modelItem => item.Street)</a>
                        </td>
                        <td>
                            <a href="@Html.DisplayFor(modelItem => item.Boliga.BoligaHyperlink)" target="_blank">@Html.DisplayFor(modelItem => item.Street)</a>
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Type.BoligTypeNavn)
                        </td>
                    </tr>
                }
            }

        </tbody>
    </table>
</div>

Views/Shared/_Layout.cshtml
@inject SignInManager<ApplicationUser> signInManager;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BeckITEjendomsmæglerApplikation</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Hjem</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Address" asp-action="Index">Boligliste</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="FileUpload" asp-action="Index">Filer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Calendar" asp-action="Index">Kalender</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-controller="Search" asp-action="Search">Søgning</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        @if (signInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-action="EditProfile" asp-controller="account">@User.Identity.Name</a>
                            </li>
                            <li class="nav-item">
                                <form method="post" asp-controller="account" asp-action="logout">
                                    <button type="submit" class="nav-link btn btn-link py-0" style="width:auto">
                                        Logout 
                                    </button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-action="Registration" asp-controller="account">Registrering</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-action="Login" asp-controller="account">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>